// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// getGFishercoef_cached_cpp
Rcpp::List getGFishercoef_cached_cpp(arma::vec D, arma::mat M, std::string p_type);
RcppExport SEXP _GFisher_getGFishercoef_cached_cpp(SEXP DSEXP, SEXP MSEXP, SEXP p_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    Rcpp::traits::input_parameter< std::string >::type p_type(p_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(getGFishercoef_cached_cpp(D, M, p_type));
    return rcpp_result_gen;
END_RCPP
}
// clear_GFisher_cache
int clear_GFisher_cache();
RcppExport SEXP _GFisher_clear_GFisher_cache() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(clear_GFisher_cache());
    return rcpp_result_gen;
END_RCPP
}
// get_GFisher_cache_size
int get_GFisher_cache_size();
RcppExport SEXP _GFisher_get_GFisher_cache_size() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_GFisher_cache_size());
    return rcpp_result_gen;
END_RCPP
}
// get_GFisher_cache_stats
Rcpp::List get_GFisher_cache_stats();
RcppExport SEXP _GFisher_get_GFisher_cache_stats() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_GFisher_cache_stats());
    return rcpp_result_gen;
END_RCPP
}
// getGFisherlam_cpp
List getGFisherlam_cpp(arma::vec D, arma::vec w, arma::mat M, arma::mat GM);
RcppExport SEXP _GFisher_getGFisherlam_cpp(SEXP DSEXP, SEXP wSEXP, SEXP MSEXP, SEXP GMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type GM(GMSEXP);
    rcpp_result_gen = Rcpp::wrap(getGFisherlam_cpp(D, w, M, GM));
    return rcpp_result_gen;
END_RCPP
}
// compute_coefficients_two_cpp
arma::vec compute_coefficients_two_cpp(arma::vec D, int coeff_type);
RcppExport SEXP _GFisher_compute_coefficients_two_cpp(SEXP DSEXP, SEXP coeff_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type coeff_type(coeff_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_coefficients_two_cpp(D, coeff_type));
    return rcpp_result_gen;
END_RCPP
}
// compute_coefficients_one_cpp
arma::vec compute_coefficients_one_cpp(arma::vec D, int coeff_type);
RcppExport SEXP _GFisher_compute_coefficients_one_cpp(SEXP DSEXP, SEXP coeff_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type coeff_type(coeff_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_coefficients_one_cpp(D, coeff_type));
    return rcpp_result_gen;
END_RCPP
}
// getGFisherGM_cached_cpp
arma::mat getGFisherGM_cached_cpp(arma::vec D, arma::vec w, arma::mat M, std::string p_type);
RcppExport SEXP _GFisher_getGFisherGM_cached_cpp(SEXP DSEXP, SEXP wSEXP, SEXP MSEXP, SEXP p_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    Rcpp::traits::input_parameter< std::string >::type p_type(p_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(getGFisherGM_cached_cpp(D, w, M, p_type));
    return rcpp_result_gen;
END_RCPP
}
// getGFisherGM_cpp
arma::mat getGFisherGM_cpp(arma::vec D, arma::vec w, arma::mat M, std::string p_type);
RcppExport SEXP _GFisher_getGFisherGM_cpp(SEXP DSEXP, SEXP wSEXP, SEXP MSEXP, SEXP p_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    Rcpp::traits::input_parameter< std::string >::type p_type(p_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(getGFisherGM_cpp(D, w, M, p_type));
    return rcpp_result_gen;
END_RCPP
}
// getGFishercoef_cpp
Rcpp::List getGFishercoef_cpp(arma::vec D, arma::mat M, std::string p_type);
RcppExport SEXP _GFisher_getGFishercoef_cpp(SEXP DSEXP, SEXP MSEXP, SEXP p_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    Rcpp::traits::input_parameter< std::string >::type p_type(p_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(getGFishercoef_cpp(D, M, p_type));
    return rcpp_result_gen;
END_RCPP
}
// p_GFisher_MR_cpp
double p_GFisher_MR_cpp(double q, arma::vec df, arma::vec w, arma::mat M, std::string p_type, int nsim, int seed);
RcppExport SEXP _GFisher_p_GFisher_MR_cpp(SEXP qSEXP, SEXP dfSEXP, SEXP wSEXP, SEXP MSEXP, SEXP p_typeSEXP, SEXP nsimSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type df(dfSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    Rcpp::traits::input_parameter< std::string >::type p_type(p_typeSEXP);
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(p_GFisher_MR_cpp(q, df, w, M, p_type, nsim, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GFisher_getGFishercoef_cached_cpp", (DL_FUNC) &_GFisher_getGFishercoef_cached_cpp, 3},
    {"_GFisher_clear_GFisher_cache", (DL_FUNC) &_GFisher_clear_GFisher_cache, 0},
    {"_GFisher_get_GFisher_cache_size", (DL_FUNC) &_GFisher_get_GFisher_cache_size, 0},
    {"_GFisher_get_GFisher_cache_stats", (DL_FUNC) &_GFisher_get_GFisher_cache_stats, 0},
    {"_GFisher_getGFisherlam_cpp", (DL_FUNC) &_GFisher_getGFisherlam_cpp, 4},
    {"_GFisher_compute_coefficients_two_cpp", (DL_FUNC) &_GFisher_compute_coefficients_two_cpp, 2},
    {"_GFisher_compute_coefficients_one_cpp", (DL_FUNC) &_GFisher_compute_coefficients_one_cpp, 2},
    {"_GFisher_getGFisherGM_cached_cpp", (DL_FUNC) &_GFisher_getGFisherGM_cached_cpp, 4},
    {"_GFisher_getGFisherGM_cpp", (DL_FUNC) &_GFisher_getGFisherGM_cpp, 4},
    {"_GFisher_getGFishercoef_cpp", (DL_FUNC) &_GFisher_getGFishercoef_cpp, 3},
    {"_GFisher_p_GFisher_MR_cpp", (DL_FUNC) &_GFisher_p_GFisher_MR_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_GFisher(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
