# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Cached Compute Hermite Polynomial Coefficients for GFisher
#'
#' Fast C++ implementation with caching for repeated df values.
#' This can significantly speed up analyses where the same df values are used repeatedly
#' (e.g., df=1,2,3 across thousands of genes).
#'
#' @param D Vector of degrees of freedom for a GFisher statistic.
#' @param M Correlation matrix of the input Z-scores.
#' @param p_type String: "two" for two-sided, "one" for one-sided input p-values.
#'
#' @return A list of 4 vectors of integrals:
#' \itemize{
#'   \item For two-sided: list(coeff2, coeff4, coeff6, coeff8)
#'   \item For one-sided: list(coeff1, coeff2, coeff3, coeff4)
#' }
#'
#' @details
#' This function provides cached computation of coefficients using the same integration
#' routines as getGFishercoef_cpp but with an efficient caching layer at the individual
#' coefficient level. When the same df value is requested multiple times, the cached result is
#' returned immediately without recomputing expensive integrals. The cache has
#' a size limit to prevent unbounded memory growth.
#'
#' Cache efficiency: For genome-wide analyses where df values are reused across
#' many tests, this caching can provide significant speedups by avoiding redundant
#' numerical integration.
#'
#' @export
getGFishercoef_cached_cpp <- function(D, M, p_type) {
    .Call(`_GFisher_getGFishercoef_cached_cpp`, D, M, p_type)
}

#' Clear GFisher Coefficient Cache
#'
#' Clears the internal cache used by getGFishercoef_cached_cpp.
#' This can be useful to free memory or force recomputation.
#'
#' @return The number of entries that were cleared from the cache.
#'
#' @export
clear_GFisher_cache <- function() {
    .Call(`_GFisher_clear_GFisher_cache`)
}

#' Get GFisher Coefficient Cache Size
#'
#' Returns the current number of entries in the coefficient cache.
#'
#' @return The number of cached coefficient values.
#'
#' @export
get_GFisher_cache_size <- function() {
    .Call(`_GFisher_get_GFisher_cache_size`)
}

#' Get GFisher Cache Statistics
#'
#' Returns detailed statistics about the coefficient cache.
#'
#' @return A list containing cache statistics:
#' \itemize{
#'   \item size: Current number of entries
#'   \item max_size: Maximum cache size before automatic clearing
#'   \item memory_kb: Approximate memory usage in KB
#'   \item fill_ratio: Percentage of max capacity used
#' }
#'
#' @export
get_GFisher_cache_stats <- function() {
    .Call(`_GFisher_get_GFisher_cache_stats`)
}

#' Fast C++ Implementation of getGFisherlam
#'
#' Computes eigenvalues needed for quadratic approximation using RcppArmadillo's
#' optimized LAPACK routines for eigenvalue decomposition.
#'
#' @param D Vector of degrees of freedom
#' @param w Vector of weights
#' @param M Correlation matrix of input Z-scores
#' @param GM Covariance matrix from getGFisherGM
#' @return List with eigenvalues (lam)
#'
#' @details
#' This function implements Algorithm from Section 3.4 of the GFisher paper:
#'
#' 1. Construct M_tilde matrix using formula (13):
#'    M_tilde_{ij} = sign(M_{ij}) * sqrt(|GM_{ij}| / (min(d_i, d_j) * 2))
#'
#' 2. Ensure M_tilde is a valid correlation matrix (values <= 1, positive definite)
#'
#' 3. Compute weighted Cholesky: WM_chol = chol(M_tilde) * diag(sqrt(w))
#'
#' 4. Extract eigenvalues from WM_chol^T * WM_chol
#'
#' 5. For max(D) > 1, add additional eigenvalues for higher degrees of freedom
#'
#' 6. Filter out small eigenvalues (< 1e-10)
#'
#' The C++ implementation uses Armadillo's eig_sym() which directly calls
#' optimized LAPACK routines, providing significant speedup over R's eigen().
#'
#' @references
#' Zhang, H., & Wu, Z. (2023). The generalized Fisher's combination and accurate p-value
#' calculation under dependence. Biometrics, 79(2), 1159-1172. See Section 3.4.
#'
#' @keywords internal
#' @export
getGFisherlam_cpp <- function(D, w, M, GM) {
    .Call(`_GFisher_getGFisherlam_cpp`, D, w, M, GM)
}

#' Compute Coefficient Integrals for Two-Sided P-Values (C++)
#'
#' Fast C++ implementation of coefficient calculations using Gauss-Legendre quadrature.
#' For two-sided p-values, computes integrals of the form:
#' \deqn{I_j(k) = \int_{-8}^{8} F^{-1}_{d_j}(\Phi(x^2)) \phi(x) H_k(x) dx}
#'
#' @param D Vector of degrees of freedom
#' @param coeff_type Integer: 2, 4, 6, or 8 for the Hermite polynomial order
#' @return Vector of coefficient integrals
#' @keywords internal
compute_coefficients_two_cpp <- function(D, coeff_type) {
    .Call(`_GFisher_compute_coefficients_two_cpp`, D, coeff_type)
}

#' Compute Coefficient Integrals for One-Sided P-Values (C++)
#'
#' Fast C++ implementation for one-sided p-values.
#' Computes integrals of the form:
#' \deqn{I_j(k) = \int_{-8}^{8} F^{-1}_{d_j}(\Phi(x)) \phi(x) H_k(x) dx}
#'
#' @param D Vector of degrees of freedom
#' @param coeff_type Integer: 1, 2, 3, or 4 for the Hermite polynomial order
#' @return Vector of coefficient integrals
#' @keywords internal
compute_coefficients_one_cpp <- function(D, coeff_type) {
    .Call(`_GFisher_compute_coefficients_one_cpp`, D, coeff_type)
}

#' Cached C++ Implementation of getGFisherGM
#'
#' Computes covariance matrix for weighted GFisher statistics using optimized
#' numerical integration with caching for repeated df values.
#'
#' @param D Vector of degrees of freedom
#' @param w Vector of weights
#' @param M Correlation matrix
#' @param p_type String: "two" for two-sided, "one" for one-sided
#' @return Covariance matrix GM
#'
#' @details
#' This function implements the covariance matrix calculation with automatic
#' caching. It retrieves coefficients using the cached version
#' \code{getGFishercoef_cached_cpp}, which checks the cache first before
#' computing. For analyses with repeated df values (e.g., analyzing thousands
#' of gene sets with df=2), this provides significant speedup through caching.
#'
#' For two-sided p-values, uses cached coefficients coeff2, coeff4, coeff6, coeff8.
#' For one-sided p-values, uses cached coeff1, coeff2, coeff3, coeff4.
#'
#' The covariance matrix is built using Hermite polynomial expansions as described
#' in the GFisher paper.
#'
#' @references
#' Zhang, H., & Wu, Z. (2023). The generalized Fisher's combination and accurate p-value
#' calculation under dependence. Biometrics, 79(2), 1159-1172.
#'
#' @keywords internal
#' @export
getGFisherGM_cached_cpp <- function(D, w, M, p_type) {
    .Call(`_GFisher_getGFisherGM_cached_cpp`, D, w, M, p_type)
}

#' Non-Cached C++ Implementation of getGFisherGM
#'
#' Computes covariance matrix for weighted GFisher statistics using optimized
#' numerical integration WITHOUT caching (robust fallback version).
#'
#' @param D Vector of degrees of freedom
#' @param w Vector of weights
#' @param M Correlation matrix
#' @param p_type String: "two" for two-sided, "one" for one-sided
#' @return Covariance matrix GM
#'
#' @details
#' This function implements the covariance matrix calculation without caching.
#' It calls \code{getGFishercoef_cpp()} which always computes coefficients fresh
#' without checking the cache. This version is used as a fallback if the cached
#' version encounters issues (extremely rare).
#'
#' This function shares the same coefficient computation logic with the cached
#' version, ensuring consistency. The only difference is the absence of caching,
#' making it simpler and more robust for fallback scenarios.
#'
#' For two-sided p-values, computes coefficients coeff2, coeff4, coeff6, coeff8.
#' For one-sided p-values, computes coeff1, coeff2, coeff3, coeff4.
#'
#' @references
#' Zhang, H., & Wu, Z. (2023). The generalized Fisher's combination and accurate p-value
#' calculation under dependence. Biometrics, 79(2), 1159-1172.
#'
#' @keywords internal
#' @export
getGFisherGM_cpp <- function(D, w, M, p_type) {
    .Call(`_GFisher_getGFisherGM_cpp`, D, w, M, p_type)
}

#' Compute Hermite Polynomial Coefficients for GFisher (C++)
#'
#' Fast C++ implementation of coefficient calculations for GFisher.
#' This function computes the raw coefficient integrals needed for
#' computing covariances between GFisher statistics.
#'
#' @param D Vector of degrees of freedom for a GFisher statistic.
#' @param M Correlation matrix of the input Z-scores.
#' @param p_type String: "two" for two-sided, "one" for one-sided input p-values.
#'
#' @return A list of 4 vectors of integrals:
#' \itemize{
#'   \item For two-sided: list(coeff2, coeff4, coeff6, coeff8)
#'   \item For one-sided: list(coeff1, coeff2, coeff3, coeff4)
#' }
#'
#' @details
#' This function implements the literal calculation of integrals in formula (7)
#' of the GFisher paper. Uses composite Gauss-Legendre quadrature for numerical
#' integration, providing substantial speedup over R's integrate() function.
#'
#' For two-sided p-values, computes:
#' \deqn{I_j(k) = \int_{-8}^{8} F^{-1}_{d_j}(\Phi(x^2)) \phi(x) H_k(x) dx}
#'
#' For one-sided p-values, computes:
#' \deqn{I_j(k) = \int_{-8}^{8} F^{-1}_{d_j}(\Phi(x)) \phi(x) H_k(x) dx}
#'
#' If a single degree of freedom is provided, it is replicated to match
#' the dimension of M.
#'
#' @references
#' Zhang, H., & Wu, Z. (2023). The generalized Fisher's combination and accurate p-value
#' calculation under dependence. Biometrics, 79(2), 1159-1172.
#'
#' @keywords internal
#' @export
getGFishercoef_cpp <- function(D, M, p_type) {
    .Call(`_GFisher_getGFishercoef_cpp`, D, M, p_type)
}

#' Fast C++ Implementation of p.GFisher Method="MR"
#'
#' Computes p-value using simulation-assisted moment ratio matching in C++.
#' This function provides substantial speedup over the pure R implementation
#' by vectorizing operations and avoiding apply() loops.
#'
#' @param q Observed GFisher statistic
#' @param df Vector of degrees of freedom
#' @param w Vector of weights
#' @param M Correlation matrix
#' @param p_type String: "two" for two-sided, "one" for one-sided
#' @param nsim Number of simulations (default 50000)
#' @param seed Random seed (0 = no seed)
#' @return P-value
#'
#' @details
#' This function implements the simulation-based moment ratio (MR) method for calculating
#' GFisher p-values under dependence. The algorithm:
#'
#' \enumerate{
#'   \item Generate null distribution: znull ~ N(0, M) using Cholesky decomposition
#'   \item Transform to p-values based on p_type (two-sided or one-sided)
#'   \item Apply chi-square transformations with specified degrees of freedom
#'   \item Compute weighted Fisher statistics: sum(w * pp_trans)
#'   \item Calculate first 4 moments from the null distribution
#'   \item Fit gamma distribution using moment matching
#'   \item Compute p-value from the gamma approximation
#' }
#'
#' \strong{Performance}:
#' This C++ implementation is substantially faster than the R version due to:
#' \itemize{
#'   \item Vectorized matrix operations via Armadillo
#'   \item Elimination of apply() loops
#'   \item Efficient memory layout
#'   \item Optimized BLAS/LAPACK routines
#' }
#'
#' \strong{Reproducibility}:
#' When the same seed is used, C++ and R versions produce
#' identical results (within machine precision).
#'
#' @references
#' Zhang, H., & Wu, Z. (2023). The generalized Fisher's combination and accurate p-value
#' calculation under dependence. Biometrics, 79(2), 1159-1172.
#'
#' @keywords internal
#' @export
p_GFisher_MR_cpp <- function(q, df, w, M, p_type = "two", nsim = 50000L, seed = 0L) {
    .Call(`_GFisher_p_GFisher_MR_cpp`, q, df, w, M, p_type, nsim, seed)
}

